//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E16028Proj.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ChinookEntities : DbContext
    {
        public ChinookEntities()
            : base("name=ChinookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoiceLine> InvoiceLines { get; set; }
        public virtual DbSet<MediaType> MediaTypes { get; set; }
        public virtual DbSet<Playlist> Playlists { get; set; }
        public virtual DbSet<Track> Tracks { get; set; }
        public virtual DbSet<InvoiceStatistic> InvoiceStatistics { get; set; }
    
        public virtual ObjectResult<spArtists_Search_Result> spArtists_Search(Nullable<int> quant, Nullable<System.DateTime> time1, Nullable<System.DateTime> time2)
        {
            var quantParameter = quant.HasValue ?
                new ObjectParameter("Quant", quant) :
                new ObjectParameter("Quant", typeof(int));
    
            var time1Parameter = time1.HasValue ?
                new ObjectParameter("time1", time1) :
                new ObjectParameter("time1", typeof(System.DateTime));
    
            var time2Parameter = time2.HasValue ?
                new ObjectParameter("time2", time2) :
                new ObjectParameter("time2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spArtists_Search_Result>("spArtists_Search", quantParameter, time1Parameter, time2Parameter);
        }
    
        public virtual ObjectResult<spCustomer_Search_Result> spCustomer_Search(Nullable<System.DateTime> time1, Nullable<System.DateTime> time2)
        {
            var time1Parameter = time1.HasValue ?
                new ObjectParameter("time1", time1) :
                new ObjectParameter("time1", typeof(System.DateTime));
    
            var time2Parameter = time2.HasValue ?
                new ObjectParameter("time2", time2) :
                new ObjectParameter("time2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCustomer_Search_Result>("spCustomer_Search", time1Parameter, time2Parameter);
        }
    
        public virtual ObjectResult<spGenre_Search_Result> spGenre_Search()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGenre_Search_Result>("spGenre_Search");
        }
    
        public virtual ObjectResult<spInvoice_Search_Result> spInvoice_Search(string cusName, string empName, Nullable<System.DateTime> time1, Nullable<System.DateTime> time2)
        {
            var cusNameParameter = cusName != null ?
                new ObjectParameter("cusName", cusName) :
                new ObjectParameter("cusName", typeof(string));
    
            var empNameParameter = empName != null ?
                new ObjectParameter("empName", empName) :
                new ObjectParameter("empName", typeof(string));
    
            var time1Parameter = time1.HasValue ?
                new ObjectParameter("time1", time1) :
                new ObjectParameter("time1", typeof(System.DateTime));
    
            var time2Parameter = time2.HasValue ?
                new ObjectParameter("time2", time2) :
                new ObjectParameter("time2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spInvoice_Search_Result>("spInvoice_Search", cusNameParameter, empNameParameter, time1Parameter, time2Parameter);
        }
    
        public virtual ObjectResult<spInvStat_Search_Result> spInvStat_Search()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spInvStat_Search_Result>("spInvStat_Search");
        }
    
        public virtual ObjectResult<spMonthTrack_Search_Result> spMonthTrack_Search(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMonthTrack_Search_Result>("spMonthTrack_Search", yearParameter);
        }
    
        public virtual ObjectResult<spTrack_Search_Result> spTrack_Search(Nullable<System.DateTime> time1, Nullable<System.DateTime> time2)
        {
            var time1Parameter = time1.HasValue ?
                new ObjectParameter("time1", time1) :
                new ObjectParameter("time1", typeof(System.DateTime));
    
            var time2Parameter = time2.HasValue ?
                new ObjectParameter("time2", time2) :
                new ObjectParameter("time2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spTrack_Search_Result>("spTrack_Search", time1Parameter, time2Parameter);
        }
    }
}
